{% set version = "2.2.0" %}

package:
  name: neutcurve
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/neutcurve/neutcurve-{{ version }}.tar.gz
  sha256: ad52a3b38fe0482d962cd9cc8ac5de8e39fb6006367b7c392a59bc0fa8f93517

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dmslogo >=0.2.1
    - matplotlib-base >=3.0.0
    - openpyxl >=3.0
    - pandas >=1.0.1
    - pyyaml >=3.13
    - scipy >=1.1.0
    - xlrd >=1.2

test:
  commands:
    - pip check
  imports:
    - neutcurve
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/jbloomlab/neutcurve
  summary: Plot and fit neutralization curves.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - danielnachun
